version: '2'


# persistence for mysql and zentao
volumes:
  zentao_db:
    driver: local
  zentao_data:
    driver: local


networks:
  zentao-net:
    driver: bridge


services:

# mysql service for zentao
  zentao-mysql:
    image: mysql:5.7
    container_name: zentao-mysql
    hostname: db.zentao.localhost
    ports:
      - '3307:3306'
    volumes:
      - 'zentao_db:/var/lib/mysql'
    environment:
      - MYSQL_HOST=db.zentao.localhost
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=zentao
      - MYSQL_USER=zentao
      - MYSQL_PASSWORD=secret
      - MARIADB_MYSQL_LOCALHOST_USER=true
      - MYSQL_ROOT_PASSWORD=pass4Zentao
    networks:
      - zentao-net

# zentao service
  zentao:
    image: hub.qucheng.com/app/quickon-zentao:${TAG:-latest}
    container_name: zentao
    hostname: 'zentao.localhost'
    ports:
      - '8888:80'
    volumes:
      - 'zentao_data:/data'
    depends_on:
      - zentao-mysql
    environment:
      - MYSQL_HOST=db.zentao.localhost
      - MYSQL_PORT=3306
      - MYSQL_DB=zentao
      - MYSQL_USER=zentao
      - MYSQL_PASSWORD=secret
      - PHP_MAX_EXECUTION_TIME=120
      - PHP_MEMORY_LIMIT=512M
      - PHP_POST_MAX_SIZE=128M
      - PHP_UPLOAD_MAX_FILESIZE=128M
      - LDAP_ENABLED=false
        #- EASYSOFT_DEBUG=true
        #- DEBUG=1
      - IS_CONTAINER=true
    networks:
      - zentao-net
